name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:    
    - uses: actions/checkout@v2    
    - name: npm install
      run: |
        sudo npm install -g hexo-cli
        npm install
    - name: hexo deploy
      run: |
       hexo cl
       hexo g
       cp ./README.md ./public/README.md

    - name: publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:realwds/blog.git
        BRANCH: gh-pages
        FOLDER: public        
        SSH_PRIVATE_KEY: ${{ secrets.publish }}
